title: "Ninghan Zhong"
author: "Ninghan Zhong"
description: "Ninghan Zhong | Contact"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "Home"}
  - {file: "bio.md", title: "Biography"}
  - {title: "Publications", url: "https://scholar.google.ca/citations?user=8zyHdjoAAAAJ&hl=en&oi=ao"}
  - {file: "projects.md", title: "Projects"}
  - {title: "CV", url: "https://ivaniz.github.io/cv.pdf"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "n5zhong@uwaterloo.ca"}
  - {title: Github, icon: github, url: "https://github.com/IvanIZ"}
  - {icon: linkedin, url: "https://www.linkedin.com/in/ninghanzhong/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
